import type { Metadata } from "next";
import "../globals.css";
import { HeaderLogin } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;400;700;900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;400;700;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased font-jakarta font-inter">
        <main>
            <div className="bg-[url('/bg-image.png')] bg-cover  w-full h-full">
                <HeaderLogin/>
                {children}
            </div>
        </main>
      </body>
    </html>
  );
}
